server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: netty-visualizer
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

logging:
  level:
    com.yueny.stars.netty.visualizer: DEBUG
    org.springframework.web.socket: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"